/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Game = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'genre' : IDL.Text,
  'rating' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
  'gameName' : IDL.Text,
});
export const NewsPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'summary' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGame' : IDL.Func([Game], [], []),
  'addLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'addNewsPost' : IDL.Func([NewsPost], [], []),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getNews' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'genre' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
    'gameName' : IDL.Text,
  });
  const NewsPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'summary' : IDL.Text,
  });
  
  return IDL.Service({
    'addGame' : IDL.Func([Game], [], []),
    'addLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'addNewsPost' : IDL.Func([NewsPost], [], []),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getNews' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };