/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Game {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'genre' : string,
  'rating' : bigint,
}
export interface LeaderboardEntry {
  'rank' : bigint,
  'score' : bigint,
  'playerName' : string,
  'gameName' : string,
}
export interface NewsPost {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'summary' : string,
}
export interface _SERVICE {
  'addGame' : ActorMethod<[Game], undefined>,
  'addLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'addNewsPost' : ActorMethod<[NewsPost], undefined>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getNews' : ActorMethod<[], Array<NewsPost>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];